name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2

  native_build:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup install stable
      - uses: Swatinem/rust-cache@v2

      - name: Build in Release profile with all features enabled
        run: cargo build --release --all-features

      - name: Determine tag name
        id: determine_tag_name
        shell: bash # Or it won't work on Windows
        run: echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Rename Release (Unix)
        run: |
          cargo install default-target
          mkdir -p assets
          FILENAME=falconf-${{ steps.determine_tag_name.outputs.tag_name }}-$(default-target)
          mv target/release/falconf assets
          cd assets
          tar --format=ustar -czf $FILENAME.tar.gz falconf
          rm falconf
          ls .
        if: ${{ matrix.platform != 'windows-latest' }}
        shell: bash

      #      - name: Rename Release (Windows)
      #        run: |
      #          cargo install default-target
      #          mkdir assets
      #          FILENAME=falconf-${{steps.determine_tag_name.outputs.tag_name}}-$(default-target)
      #          mv target/release/falconf.exe assets/falconf.exe
      #          cd assets
      #          powershell Compress-Archive -Path * -Destination ${FILENAME}.zip
      #          rm falconf.exe
      #          ls .
      #        if: ${{ matrix.platform == 'windows-latest' }}
      #        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.determine_tag_name.outputs.tag_name }}
          files: assets/*
  
  publish_crates_io:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update toolchain
        run: rustup install stable
      - uses: Swatinem/rust-cache@v2

      - name: cargo login
        run: |-
          echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login

      - name: "cargo publish"
        run: cargo publish
