name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Set up toolchain
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
      - name: Format (cargo fmt)
        run: cargo fmt --verbose --all -- --check
      - name: Build (cargo build)
        run: cargo build --verbose
      - name: Lint (cargo clippy)
        # Has to be nightly because https://github.com/rust-lang/rust-clippy/pull/14407 is not released on stable yet
        # TODO: remove dependency on nightly when this PR is released to stable (below as well)
        run: cargo +nightly clippy --verbose --all-features -- -D warnings
      - name: Lint tests (cargo clippy)
        run: cargo +nightly clippy --verbose --all-features --tests -- -D warnings
      - name: Run tests (cargo test)
        run: cargo test --verbose
