name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Set up toolchain
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
      - name: Format (cargo fmt)
        run: cargo fmt --verbose --all -- --check
      - name: Build (cargo build)
        run: cargo build --verbose
      - name: Lint (cargo clippy)
        # Has to be nightly because the `clippy::missing_panics_doc` lint works differently
        run: cargo +nightly clippy --verbose --all-features -- -D warnings
      - name: Run tests (cargo test)
        run: cargo test --verbose
